version: '3.9'

services:
  api-gateway-knative-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: caiomarcatti12/api-gateway-knative-docker:dev
    container_name: api-gateway-knative-docker
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
